stages:
  - build

variables:
  GIT_STRATEGY: fetch
  GIT_SSL_NO_VERIFY: "1"
  IMAGE_NAME: dockerhub.datagrand.com/caojunjie/electron-best-practice/$CI_COMMIT_REF_NAME

before_script:
  - docker login -u $ci_harbor_pull_u -p $ci_harbor_pull_p http://dockerhub.datagrand.com
  - echo 'commit id full:' $CI_COMMIT_SHA
  - export DATE=$(git log -1 --pretty=format:"%ad" --date=format:'%Y%m%d' $CI_COMMIT_SHA)
  - export IMAGE_TAG="ci"_$DATE"_"${CI_COMMIT_SHA:0:8}

build:linux:
  stage: build
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG -f Dockerfile.linux .
    - echo '镜像名称:' $IMAGE_NAME:$IMAGE_TAG
    - docker rm -f temp_container || true
    - docker create --name temp_container $IMAGE_NAME:$IMAGE_TAG && docker cp temp_container:/app/release release && docker rm temp_container
  allow_failure: false
  artifacts:
    name: electron-build-linux
    paths:
      - release/
    expire_in: 1 week
  only:
    - main
    - master
    - tags