FROM dockerhub.datagrand.com/ci_runner/frontend_web:16.14.0

WORKDIR /app

COPY ./package.json ./yarn.lock /app/

RUN yarn config set registry https://registry.npmmirror.com/ \
    && yarn install --frozen-lockfile

COPY . /app/

RUN yarn build && yarn build:linux